# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MechToast
description: > # this means to ignore newlines until "baseurl:"
  MechToast.com is the personal blog of Max Hunt.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mechtoast.com" # the base hostname & protocol for your site
github_username:  m-r-hunt

collections:
  rp_log:
    output: true
    permalink: /rp/log/:title/

# Build settings
markdown: kramdown
highlighter: rouge
timezone: Europe/London

permalink: /:categories/:title/
